# highlights.scm is based on https://github.com/nvim-treesitter/nvim-treesitter/blob/9775d5d7c724f81acdd441e7e9edefc4514e990b/queries/scss/highlights.scm

name = "SCSS"
grammar = "scss"
path_suffixes = ["scss", "sass"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
word_characters = ["-"]
block_comment = ["/* ", " */"]
prettier_parser_name = "scss"

